### ISSUE TITLE
Any references for the algorithm used?

### ISSUE THREAD

**Issue by frankxu2004** [neubig/latticelm#4]
Thanks for the great tool! 
However, I'm wondering if there are any papers that describe the algorithms used in the program. I am interested in unsupervised text/char sequence segmentation, and it would be great if you could provide some references that I could cite. 
Thanks

**Comment by neubig** [comment]
Sure, from the tool README:

Graham Neubig, Masato Mimura, Shinsuke Mori, Tatsuya Kawahara
"Learning a Language Model from Continuous Speech"
In proceedings for InterSpeech 2010

**Comment by frankxu2004** [comment]
Thanks a lot.

My fault not checking carefully the README though :(


---
Frank Xu <http://frankxfz.me>
Master candidate
ADAPT Lab <http://adapt.seiee.sjtu.edu.cn>
Computer Science and Engineering Dept.
School of Electronic Information and Electrical Engineering
Shanghai Jiao Tong University
800 Dongchuan Road,
Shanghai, China 200240
